### ISSUE TITLE
check the consistency of the timescales

### ISSUE THREAD

**Issue by mamueller** [MPIBGC-TEE/bgc_md2#70]
The different trendy datasets have different month lengths. 
In Aneeshes case the following code shows that we have 720 hours between all monthly values.
```python
times=nc.Dataset("/home/data/SDGVM/SDGVM_S2_npp.nc")["time"]
set([times[i+1]-times[i] for i in range(len(times)-1)])
```
which yields ` {720.0}`
So he has 30 day months
For Yu we have. 
```python
times=nc.Dataset("/home/data/yu/JULES-ES-1p0_S2_npp.nc")["time"]
set([(times[i+1]-times[i])/(3600*24) for i in range(len(times)-1)])
which yields 3 different values
```{29.5, 30.5, 31.0}```

In Jon's case the unit of time is "month" which makes it impossible to test how long a month is...
So he is fine...

We have to make sure that the model specific make_func_dict produces functions that grab the driver value from the right month.
(E.g. Imagine we are at day 309 of a simulation
 if a model has a constant 30 day month it will have to grab the driver value for month 11 if it had a 31 day month it would be the 10 th value instead. ) 

If we use the same time scale for all models this problem accumulates over time.
This could  also impact the model comparison plots.
The good news is that daily values are still compatible.
 
Are there other parts of the code where we have to be careful?

@Kostia:
We will have to ask everybody to do this (assign it to more people). I just chose you first since you already (re)implemented a related function in general_helpers.py. We might end up with model-specific functions but we should  figure out the minimal solution first.

**Comment by viatkin** [comment]
I checked both in the code and in the description of time variable in netcdf files.
Here I made a Google Sheet with information on how time is arranged in different models (6 models so far): 
[Time and Space Variables in TRENDY S2](https://docs.google.com/spreadsheets/d/17gDgogw8gNluG4qvYMaMXAgeeiVwfNJK30QHy9yKW6g/edit?usp=sharing)

**Comment by mamueller** [comment]
Just found 
```python
if mf in ["Aneesh_SDGVM"]: # different calculation for models with 30-day months
``` 
in function ` times_in_days_aD` in general_helpers.py
This does NOT belong there. ;-)

In general helpers NO model name should be specified, NOT A SINGLE FUNKTION there has to know about a specific model, this part clearly belongs to model specific helpers...

This is a general design principle to ensure that we do not  entangle our code and loose the generality of the common modules...

**Comment by viatkin** [comment]
We configured all models to work on a 30-day month basis (since all data is monthly or yearly). 
Commit: [b8cac5096523d9a633f63f5178b7def7d10acd40](https://github.com/MPIBGC-TEE/bgc_md2/commit/b8cac5096523d9a633f63f5178b7def7d10acd40)
